apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-torrent
  labels:
    app: transmission
spec:
  storageClassName: local-path-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi